apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: mlops-app-ingress
  namespace: default
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
spec:
  rules:
    - host: mlops.velatdicleli.com
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: mlops-app-service
                port:
                  number: 80
