apiVersion: v1
kind: Service
metadata:
  name: mlops-app-service
  namespace: default
spec:
  selector:
    app: mlops-app
  ports:
    - protocol: TCP
      port: 80
      targetPort: 7860
  type: ClusterIP
